export const courses = [
  { id: "breakfast", name: "Breakfast" },
  { id: "brunch", name: "Brunch" },
  { id: "lunch", name: "Lunch" },
  { id: "appetizer", name: "Appetizer" },
  { id: "main course", name: "Main Course" },
  { id: "dessert", name: "Dessert" },
  { id: "snack", name: "Snack" },
  { id: "beverage", name: "Beverage" },
];

export const categories = [
  { id: "bread", name: "Bread" },
  { id: "vegetarian", name: "Vegetarian" },
  { id: "vegan", name: "Vegan" },
  { id: "gluten-free", name: "Gluten-Free" },
  { id: "dairy-free", name: "Dairy-Free" },
  { id: "low-carb", name: "Low-Carb" },
  { id: "soup", name: "Soup" },
  { id: "salad", name: "Salad" },
  { id: "pasta", name: "Pasta" },
  { id: "rice", name: "Rice" },
  { id: "seafood", name: "Seafood" },
  { id: "fish", name: "Fish" },
  { id: "chicken", name: "Chicken" },
  { id: "pork", name: "Pork" },
  { id: "lamb", name: "Lamb" },
  { id: "beef", name: "Beef" },
  { id: "beverage", name: "Beverage" },
];
